// Angus Association Excel template definitions
// Each template defines: name, description, column headers, and which headers are required

export interface TemplateDefinition {
  id: string;
  name: string;
  description: string;
  sheetName: string;
  titleRow: string; // Row 1 title text
  columns: TemplateColumn[];
}

export interface TemplateColumn {
  header: string;
  required: boolean;
  description?: string;
}

export const ANGUS_TEMPLATES: TemplateDefinition[] = [
  {
    id: "angus_calving_book",
    name: "Electronic Calving Book",
    description: "Calving records — dam, sire, calf tag, sex, birth date, birth weight, calving ease",
    sheetName: "Electronic Calving Book",
    titleRow: "ELECTRONIC CALVING BOOK RECORDS",
    columns: [
      { header: "CUST CODE", required: true, description: "Your Angus Association customer code" },
      { header: "2nd CUST", required: false },
      { header: "CALF ASSN NUM", required: false, description: "Calf registration number if known" },
      { header: "CALF ASSN", required: false },
      { header: "DAM ASSN NUM", required: false, description: "Dam registration number" },
      { header: "DAM ASSN", required: false },
      { header: "DAM TAG", required: false, description: "Dam visual tag" },
      { header: "DAM BIRTH DATE", required: false },
      { header: "ET", required: false, description: "Embryo transfer (Y/N)" },
      { header: "IVF", required: false },
      { header: "ET RECIPIENT ASSN NUM", required: false },
      { header: "ET RECIPIENT ASSN", required: false },
      { header: "ET RECIPIENT TAG", required: false },
      { header: "ET RECIPIENT BIRTH DATE", required: false },
      { header: "SIRE ASSN NUM", required: false },
      { header: "SIRE ASSN", required: false },
      { header: "SIRE TAG", required: false },
      { header: "SIRE GROUP", required: false },
      { header: "CALF TAG", required: false, description: "Calf visual tag" },
      { header: "CALF SEX", required: false, description: "B=Bull, C=Cow/Heifer, S=Steer" },
      { header: "TATTOO/BRAND", required: false },
      { header: "BIRTH DATE", required: false },
      { header: "BIRTH WEIGHT", required: false },
      { header: "BIRTH GROUP CODE", required: false },
      { header: "C E", required: false, description: "Calving ease score" },
      { header: "TWIN", required: false },
      { header: "Birth Code", required: false, description: "Stillborn/death codes" },
      { header: "DAM TEAT SCORE", required: false },
      { header: "DAM UDDER SCORE", required: false },
      { header: "FOSTER?", required: false },
      { header: "FOSTER DAM ASSN NUM", required: false },
      { header: "FOSTER DAM ASSN", required: false },
      { header: "FOSTER DAM TAG", required: false },
      { header: "FOSTER DAM BIRTH DATE", required: false },
      { header: "ELEC ID", required: false, description: "840 electronic ID" },
      { header: "REGISTER CALF?", required: false },
      { header: "ANGUS NAME*", required: false },
      { header: "ARTIFICIAL INSEMINATION?*", required: false },
      { header: "PRIMARY ID TYPE*", required: false },
      { header: "SECONDARY ID TYPE", required: false },
      { header: "FIRST OWNER*", required: false },
      { header: "BULL PERMIT", required: false },
      { header: "PERMIT TYPE", required: false },
      { header: "STORE ELECTRONICALLY?*", required: false },
      { header: "EMBRYO REMOVAL DATE", required: false },
    ],
  },
  {
    id: "angus_calving_weaning",
    name: "Calving & Weaning Weights",
    description: "Full calving and weaning records with cow measurements and foot scores",
    sheetName: "Calving Weaning Weights",
    titleRow: "CALVING AND WEANING RECORDS",
    columns: [
      { header: "CUST CODE", required: true },
      { header: "2nd CUST", required: false },
      { header: "CALF ASSN NUM", required: false },
      { header: "CALF ASSN", required: false },
      { header: "DAM ASSN NUM", required: false },
      { header: "DAM ASSN", required: false },
      { header: "DAM TAG", required: false },
      { header: "DAM BIRTH DATE", required: false },
      { header: "ET", required: false },
      { header: "IVF", required: false },
      { header: "ET RECIPIENT ASSN NUM", required: false },
      { header: "ET RECIPIENT ASSN", required: false },
      { header: "ET RECIPIENT TAG", required: false },
      { header: "ET RECIPIENT BIRTH DATE", required: false },
      { header: "SIRE ASSN NUM", required: false },
      { header: "SIRE ASSN", required: false },
      { header: "SIRE TAG", required: false },
      { header: "SIRE GROUP", required: false },
      { header: "CALF TAG", required: false },
      { header: "CALF SEX", required: false },
      { header: "TATTOO/BRAND", required: false },
      { header: "BIRTH DATE", required: false },
      { header: "BIRTH WEIGHT", required: false },
      { header: "BIRTH GROUP CODE", required: false },
      { header: "C E", required: false },
      { header: "WEIGH DATE", required: false },
      { header: "WEAN WEIGHT", required: false },
      { header: "MGT CODE 1 OR 3", required: false },
      { header: "GROUP", required: false },
      { header: "TWIN", required: false },
      { header: "BIRTH CODE", required: false },
      { header: "DAM TEAT SCORE", required: false },
      { header: "DAM UDDER SCORE", required: false },
      { header: "HIP HT MEASURED DATE", required: false },
      { header: "HIP HT", required: false },
      { header: "SC MEASURED DATE", required: false },
      { header: "SC", required: false },
      { header: "CALF DOCILITY", required: false },
      { header: "CALF DISPOSAL", required: false },
      { header: "CALF DISPOSAL DATE", required: false },
      { header: "COW MEASURED DATE", required: false },
      { header: "COW WEIGHT", required: false },
      { header: "COW HEIGHT", required: false },
      { header: "COW CONDITION", required: false },
      { header: "COW DOCILITY", required: false },
      { header: "COW FOOT SCORE MSURD DATE", required: false },
      { header: "COW FOOT CLAW SET", required: false },
      { header: "COW FOOT ANGLE", required: false },
      { header: "COW FOOT SCORE DIET", required: false },
      { header: "COW FOOT SCORE COMMENT", required: false },
      { header: "COW DISPOSAL", required: false },
      { header: "COW DISPOSAL DATE", required: false },
      { header: "LOCATION", required: false },
      { header: "FOSTER?", required: false },
      { header: "FOSTER DAM ASSN NUM", required: false },
      { header: "FOSTER DAM ASSN", required: false },
      { header: "FOSTER DAM TAG", required: false },
      { header: "FOSTER DAM BIRTH DATE", required: false },
      { header: "CUSTOM VALUE", required: false },
      { header: "ELEC ID", required: false },
      { header: "REGISTER CALF?", required: false },
      { header: "ANGUS NAME*", required: false },
      { header: "ARTIFICIAL INSEMINATION?*", required: false },
      { header: "PRIMARY ID TYPE*", required: false },
      { header: "SECONDARY ID TYPE", required: false },
      { header: "FIRST OWNER*", required: false },
      { header: "BULL PERMIT", required: false },
      { header: "PERMIT TYPE", required: false },
      { header: "STORE ELECTRONICALLY?*", required: false },
      { header: "EMBRYO REMOVAL DATE", required: false },
    ],
  },
  {
    id: "angus_registration",
    name: "Registrations",
    description: "Register calves — tag, sex, birth date, name, sire/dam, owner",
    sheetName: "Registrations",
    titleRow: "REGISTRATIONS",
    columns: [
      { header: "CALF TAG", required: false },
      { header: "SEX*", required: true, description: "B=Bull, C=Cow/Heifer" },
      { header: "BIRTH DATE*", required: true },
      { header: "ANGUS NAME*", required: true },
      { header: "PRIMARY ID*", required: true, description: "T=Tattoo, E=EID, etc." },
      { header: "TATTOO/ BRAND*", required: true },
      { header: "840 EID", required: false },
      { header: "SECONDARY ID", required: false },
      { header: "ARTIFICIAL INSEMINATION?*", required: true },
      { header: "TWIN INDICATOR*", required: true },
      { header: "SIRE REG*", required: true },
      { header: "SIRE NAME", required: false },
      { header: "DAM TAG", required: false },
      { header: "DAM TATTOO", required: false },
      { header: "DAM REG*", required: true },
      { header: "DAM NAME", required: false },
      { header: "FIRST OWNER*", required: true },
      { header: "BULL PERMIT", required: false },
      { header: "PERMIT TYPE", required: false },
      { header: "EMBRYO TRANSPLANT?*", required: true },
      { header: "IVF?", required: false },
      { header: "EMBRYO REMOVAL DATE", required: false },
      { header: "STORE ELECTRONICALLY?*", required: true },
      { header: "BIRTH WEIGHT", required: false },
      { header: "BIRTH GROUP CODE", required: false },
      { header: "CALVING EASE", required: false },
    ],
  },
  {
    id: "angus_breeding",
    name: "Breeding Records",
    description: "Breeding season data — cow, preg check, AI sires, pasture sires, ET donors",
    sheetName: "Breeding",
    titleRow: "BREEDING RECORDS",
    columns: [
      { header: "CUSTOMER CODE", required: true },
      { header: "SEASON", required: false },
      { header: "YEAR", required: false },
      { header: "GROUP CODE", required: false },
      { header: "COW TAG", required: false },
      { header: "COW ASSN NUMBER", required: false },
      { header: "COW ASSN", required: false },
      { header: "COW BIRTH DATE", required: false },
      { header: "PREG CHECK DATE", required: false },
      { header: "DAYS PREG", required: false },
      { header: "OPEN", required: false },
      { header: "DISPOSAL CODE", required: false },
      { header: "DISPOSAL DATE", required: false },
      { header: "PASTURE CODE", required: false },
      { header: "FLUSH", required: false },
      { header: "AI SIRE ASSN NUMBER 1", required: false },
      { header: "AI SIRE ASSN 1", required: false },
      { header: "AI SIRE TAG 1", required: false },
      { header: "AI DATE 1", required: false },
      { header: "AI SYNC 1", required: false },
      { header: "PASTURE SIRE ASSN NUMBER 1", required: false },
      { header: "PASTURE SIRE ASSN 1", required: false },
      { header: "PASTURE SIRE TAG 1", required: false },
      { header: "PASTURE DATE IN 1", required: false },
      { header: "PASTURE DATE OUT 1", required: false },
      { header: "ELEC ID", required: false },
    ],
  },
  {
    id: "angus_cow_data",
    name: "Cow Data",
    description: "Cow measurements — weight, height, condition, docility, disposal, foot scores",
    sheetName: "Cow Data",
    titleRow: "COW DATA RECORDS",
    columns: [
      { header: "CUSTOMER", required: true },
      { header: "DAM TAG", required: false },
      { header: "DAM ASSN", required: false },
      { header: "DAM ASSN NUMBER", required: false },
      { header: "DAM TATTOO", required: false },
      { header: "BIRTH DATE", required: false },
      { header: "MEASURED DATE", required: false },
      { header: "COW WEIGHT", required: false },
      { header: "COW HEIGHT", required: false },
      { header: "CONDITION", required: false },
      { header: "DOCILITY", required: false },
      { header: "DISPOSAL", required: false },
      { header: "DISPOSAL DATE", required: false },
      { header: "ELEC ID", required: false },
      { header: "FS MSURD DATE", required: false },
      { header: "CLAW SET", required: false },
      { header: "FOOT ANGLE", required: false },
      { header: "DIET", required: false },
      { header: "FS COMMENT", required: false },
    ],
  },
  {
    id: "angus_yearling",
    name: "Yearling Weights",
    description: "Yearling records with weights, hip height, scrotal, foot scores, pelvic, RTS",
    sheetName: "Yearling Weights",
    titleRow: "YEARLING RECORDS",
    columns: [
      { header: "CUST CODE", required: true },
      { header: "2nd CUST", required: false },
      { header: "CALF ASSN NUM", required: false },
      { header: "CALF ASSN", required: false },
      { header: "DAM ASSN NUM", required: false },
      { header: "DAM ASSN", required: false },
      { header: "DAM TAG", required: false },
      { header: "DAM BIRTH DATE", required: false },
      { header: "SIRE ASSN NUM", required: false },
      { header: "SIRE ASSN", required: false },
      { header: "SIRE TAG", required: false },
      { header: "SIRE GROUP", required: false },
      { header: "CALF TAG", required: false },
      { header: "CALF SEX", required: false },
      { header: "TATTOO /BRAND", required: false },
      { header: "BIRTH DATE", required: false },
      { header: "TWIN", required: false },
      { header: "ET", required: false },
      { header: "IVF", required: false },
      { header: "WEIGH DATE", required: false },
      { header: "WEIGHT", required: false },
      { header: "GROUP", required: false },
      { header: "HIP HT MEASURE DATE", required: false },
      { header: "HIP HT", required: false },
      { header: "SC MEASURED DATE", required: false },
      { header: "SC", required: false },
      { header: "CALF DOCILITY", required: false },
      { header: "ELEC ID", required: false },
    ],
  },
  {
    id: "angus_carcass",
    name: "Carcass Records",
    description: "Carcass data — marbling, quality grade, hot weight, backfat, ribeye, yield grade",
    sheetName: "CarcassWeights",
    titleRow: "CARCASS RECORDS",
    columns: [
      { header: "CUST CODE", required: true },
      { header: "HARVEST DATE", required: false },
      { header: "CALF ASSN NUM", required: false },
      { header: "CALF ASSN", required: false },
      { header: "GROUP", required: false },
      { header: "DAM ASSN NUM", required: false },
      { header: "DAM ASSN", required: false },
      { header: "SIRE ASSN NUM*", required: false },
      { header: "SIRE ASSN", required: false },
      { header: "SIRE GROUP", required: false },
      { header: "CALF TAG", required: false },
      { header: "CALF SEX", required: false },
      { header: "CALF BIRTH DATE", required: false },
      { header: "MARB", required: false },
      { header: "QUALITY GRADE", required: false },
      { header: "HOT WT", required: false },
      { header: "BACKFAT", required: false },
      { header: "RIBEYE", required: false },
      { header: "KPH", required: false },
      { header: "HARVEST WT", required: false },
      { header: "YIELD GRADE", required: false },
      { header: "FEEDLOT ID", required: false },
      { header: "NON CONFORM", required: false },
      { header: "PLANT LOC", required: false },
      { header: "ELEC ID", required: false },
    ],
  },
  {
    id: "angus_scrotal",
    name: "Scrotal Records",
    description: "Scrotal circumference measurements for bulls",
    sheetName: "Scrotal",
    titleRow: "SCROTAL RECORDS",
    columns: [
      { header: "CUST CODE", required: true },
      { header: "CALF ASSN NUM", required: false },
      { header: "CALF ASSN", required: false },
      { header: "DAM ASSN NUM", required: false },
      { header: "DAM ASSN", required: false },
      { header: "DAM TAG", required: false },
      { header: "CALF TAG", required: false },
      { header: "TATTOO", required: false },
      { header: "BIRTH DATE", required: false },
      { header: "SC MEASURED DATE", required: false },
      { header: "SC", required: false },
      { header: "ELEC ID", required: false },
    ],
  },
  {
    id: "angus_foot_score",
    name: "Foot Score Entry",
    description: "Foot claw set and angle scores",
    sheetName: "FOOTSCORELIST",
    titleRow: "FOOT SCORE ENTRY LIST",
    columns: [
      { header: "CUST ID", required: true },
      { header: "2nd CUST ID", required: false },
      { header: "ASSN *", required: false },
      { header: "ASSN NUM *", required: false },
      { header: "TAG *", required: true },
      { header: "TATT", required: false },
      { header: "ELEC ID", required: false },
      { header: "BIRTH DATE *", required: true },
      { header: "SEX *", required: true },
      { header: "DAM ASSN *", required: false },
      { header: "DAM ASSN NUM *", required: false },
      { header: "DAM TAG", required: false },
      { header: "SIRE ASSN", required: false },
      { header: "SIRE ASSN NUM", required: false },
      { header: "SIRE TAG", required: false },
      { header: "SIRE GROUP*", required: false },
      { header: "MSURD DATE *", required: true },
      { header: "CLAW SET*", required: true },
      { header: "FOOT ANGLE *", required: true },
      { header: "DIET*", required: true },
      { header: "COMMENT", required: false },
    ],
  },
];

// Helper: get template by ID
export const getAngusTemplate = (id: string): TemplateDefinition | undefined =>
  ANGUS_TEMPLATES.find((t) => t.id === id);
