// American Angus Association Excel template definitions
// Source: Official AAA sample spreadsheets
// Each template defines: name, description, and required/optional columns
// Note: Some templates have metadata rows before the actual header row

export interface TemplateColumn {
  name: string;
  required: boolean;
  description?: string;
}

export interface BreedTemplate {
  id: string;
  name: string;
  association: string;
  description: string;
  headerRow: number; // 0-indexed row where actual column headers live
  columns: TemplateColumn[];
}

export const ANGUS_TEMPLATES: BreedTemplate[] = [
  {
    id: "aaa_calving_weaning",
    name: "Calving & Weaning Records",
    association: "American Angus Association",
    description: "Birth weights, weaning weights, calving ease, cow data, and calf registration in one sheet.",
    headerRow: 1,
    columns: [
      { name: "CUST CODE", required: true },
      { name: "2nd CUST", required: false },
      { name: "CALF ASSN NUM", required: false, description: "Calf registration number if already registered" },
      { name: "CALF ASSN", required: false, description: "Association code (e.g. AAA)" },
      { name: "DAM ASSN NUM", required: true, description: "Dam registration number" },
      { name: "DAM ASSN", required: true, description: "Dam association code" },
      { name: "DAM TAG", required: true },
      { name: "DAM BIRTH DATE", required: false },
      { name: "ET", required: false, description: "Y if embryo transfer" },
      { name: "IVF", required: false },
      { name: "ET RECIPIENT ASSN NUM", required: false },
      { name: "ET RECIPIENT ASSN", required: false },
      { name: "ET RECIPIENT TAG", required: false },
      { name: "ET RECIPIENT BIRTH DATE", required: false },
      { name: "SIRE ASSN NUM", required: true, description: "Sire registration number" },
      { name: "SIRE ASSN", required: true },
      { name: "SIRE TAG", required: false },
      { name: "SIRE GROUP", required: false },
      { name: "CALF TAG", required: true },
      { name: "CALF SEX", required: true, description: "B=Bull, H=Heifer, S=Steer" },
      { name: "TATTOO/BRAND", required: false },
      { name: "BIRTH DATE", required: true },
      { name: "BIRTH WEIGHT", required: true },
      { name: "BIRTH GROUP CODE", required: false },
      { name: "C E", required: false, description: "Calving ease score" },
      { name: "WEIGH DATE", required: false },
      { name: "WEAN WEIGHT", required: false },
      { name: "MGT CODE 1 OR 3", required: false },
      { name: "GROUP", required: false },
      { name: "TWIN", required: false },
      { name: "BIRTH CODE", required: false },
      { name: "DAM TEAT SCORE", required: false },
      { name: "DAM UDDER SCORE", required: false },
      { name: "HIP HT MEASURED DATE", required: false },
      { name: "HIP HT", required: false },
      { name: "SC MEASURED DATE", required: false },
      { name: "SC", required: false, description: "Scrotal circumference" },
      { name: "CALF DOCILITY", required: false },
      { name: "CALF DISPOSAL", required: false },
      { name: "CALF DISPOSAL DATE", required: false },
      { name: "COW MEASURED DATE", required: false },
      { name: "COW WEIGHT", required: false },
      { name: "COW HEIGHT", required: false },
      { name: "COW CONDITION", required: false },
      { name: "COW DOCILITY", required: false },
      { name: "COW FOOT SCORE MSURD DATE", required: false },
      { name: "COW FOOT CLAW SET", required: false },
      { name: "COW FOOT ANGLE", required: false },
      { name: "COW FOOT SCORE DIET", required: false },
      { name: "COW FOOT SCORE COMMENT", required: false },
      { name: "COW DISPOSAL", required: false },
      { name: "COW DISPOSAL DATE", required: false },
      { name: "LOCATION", required: false },
      { name: "FOSTER?", required: false },
      { name: "FOSTER DAM ASSN NUM", required: false },
      { name: "FOSTER DAM ASSN", required: false },
      { name: "FOSTER DAM TAG", required: false },
      { name: "FOSTER DAM BIRTH DATE", required: false },
      { name: "CUSTOM VALUE", required: false },
      { name: "ELEC ID", required: false, description: "840 EID number" },
      { name: "REGISTER CALF?", required: false },
      { name: "ANGUS NAME", required: false, description: "For calf registration" },
      { name: "ARTIFICIAL INSEMINATION?", required: false },
      { name: "PRIMARY ID TYPE", required: false },
      { name: "SECONDARY ID TYPE", required: false },
      { name: "FIRST OWNER", required: false },
      { name: "BULL PERMIT", required: false },
      { name: "PERMIT TYPE", required: false },
      { name: "STORE ELECTRONICALLY?", required: false },
      { name: "EMBRYO REMOVAL DATE", required: false },
    ],
  },
  {
    id: "aaa_breeding",
    name: "Breeding Records",
    association: "American Angus Association",
    description: "Breeding and preg check data — AI dates, pasture sires, ET info.",
    headerRow: 1,
    columns: [
      { name: "CUSTOMER CODE", required: true },
      { name: "SEASON", required: true, description: "1=Spring, 2=Fall" },
      { name: "YEAR", required: true },
      { name: "GROUP CODE", required: false },
      { name: "COW TAG", required: true },
      { name: "COW ASSN NUMBER", required: true },
      { name: "COW ASSN", required: true },
      { name: "COW BIRTH DATE", required: false },
      { name: "PREG CHECK DATE", required: false },
      { name: "DAYS PREG", required: false },
      { name: "OPEN", required: false, description: "Mark if open" },
      { name: "DISPOSAL CODE", required: false },
      { name: "DISPOSAL DATE", required: false },
      { name: "PASTURE CODE", required: false },
      { name: "FLUSH", required: false },
      { name: "AI SIRE ASSN NUMBER 1", required: false },
      { name: "AI SIRE ASSN 1", required: false },
      { name: "AI SIRE TAG 1", required: false },
      { name: "AI DATE 1", required: false },
      { name: "AI SYNC 1", required: false },
      { name: "PASTURE SIRE ASSN NUMBER 1", required: false },
      { name: "PASTURE SIRE ASSN 1", required: false },
      { name: "PASTURE SIRE TAG 1", required: false },
      { name: "PASTURE DATE IN 1", required: false },
      { name: "PASTURE DATE OUT 1", required: false },
      { name: "ELEC ID", required: false },
    ],
  },
  {
    id: "aaa_calving_book",
    name: "Electronic Calving Book",
    association: "American Angus Association",
    description: "Calving-only records — lighter version without weaning data.",
    headerRow: 1,
    columns: [
      { name: "CUST CODE", required: true },
      { name: "2nd CUST", required: false },
      { name: "CALF ASSN NUM", required: false },
      { name: "CALF ASSN", required: false },
      { name: "DAM ASSN NUM", required: true },
      { name: "DAM ASSN", required: true },
      { name: "DAM TAG", required: true },
      { name: "DAM BIRTH DATE", required: false },
      { name: "ET", required: false },
      { name: "IVF", required: false },
      { name: "ET RECIPIENT ASSN NUM", required: false },
      { name: "ET RECIPIENT ASSN", required: false },
      { name: "ET RECIPIENT TAG", required: false },
      { name: "ET RECIPIENT BIRTH DATE", required: false },
      { name: "SIRE ASSN NUM", required: true },
      { name: "SIRE ASSN", required: true },
      { name: "SIRE TAG", required: false },
      { name: "SIRE GROUP", required: false },
      { name: "CALF TAG", required: true },
      { name: "CALF SEX", required: true },
      { name: "TATTOO/BRAND", required: false },
      { name: "BIRTH DATE", required: true },
      { name: "BIRTH WEIGHT", required: false },
      { name: "BIRTH GROUP CODE", required: false },
      { name: "C E", required: false },
      { name: "TWIN", required: false },
      { name: "Birth Code", required: false },
      { name: "DAM TEAT SCORE", required: false },
      { name: "DAM UDDER SCORE", required: false },
      { name: "FOSTER?", required: false },
      { name: "FOSTER DAM ASSN NUM", required: false },
      { name: "FOSTER DAM ASSN", required: false },
      { name: "FOSTER DAM TAG", required: false },
      { name: "FOSTER DAM BIRTH DATE", required: false },
      { name: "ELEC ID", required: false },
      { name: "REGISTER CALF?", required: false },
      { name: "ANGUS NAME", required: false },
      { name: "ARTIFICIAL INSEMINATION?", required: false },
      { name: "PRIMARY ID TYPE", required: false },
      { name: "SECONDARY ID TYPE", required: false },
      { name: "FIRST OWNER", required: false },
      { name: "BULL PERMIT", required: false },
      { name: "PERMIT TYPE", required: false },
      { name: "STORE ELECTRONICALLY?", required: false },
      { name: "EMBRYO REMOVAL DATE", required: false },
    ],
  },
  {
    id: "aaa_carcass",
    name: "Carcass Records",
    association: "American Angus Association",
    description: "Harvest and carcass data — marbling, ribeye, yield grade, hot weight.",
    headerRow: 1,
    columns: [
      { name: "CUST CODE", required: true },
      { name: "HARVEST DATE", required: true },
      { name: "CALF ASSN NUM", required: false },
      { name: "CALF ASSN", required: false },
      { name: "GROUP", required: false },
      { name: "DAM ASSN NUM", required: false },
      { name: "DAM ASSN", required: false },
      { name: "SIRE ASSN NUM", required: false },
      { name: "SIRE ASSN", required: false },
      { name: "SIRE GROUP", required: false },
      { name: "CALF TAG", required: true },
      { name: "CALF SEX", required: true },
      { name: "CALF BIRTH DATE", required: false },
      { name: "MARB", required: false, description: "Marbling score" },
      { name: "QUALITY GRADE", required: false },
      { name: "HOT WT", required: false },
      { name: "BACKFAT", required: false },
      { name: "RIBEYE", required: false },
      { name: "KPH", required: false },
      { name: "HARVEST WT", required: false },
      { name: "YIELD GRADE", required: false },
      { name: "FEEDLOT ID", required: false },
      { name: "NON CONFORM", required: false },
      { name: "PLANT LOC", required: false },
      { name: "ELEC ID", required: false },
    ],
  },
  {
    id: "aaa_cow_data",
    name: "Cow Data",
    association: "American Angus Association",
    description: "Cow measurements — weight, height, condition, docility, foot scores, disposal.",
    headerRow: 1,
    columns: [
      { name: "CUSTOMER", required: true },
      { name: "DAM TAG", required: true },
      { name: "DAM ASSN", required: true },
      { name: "DAM ASSN NUMBER", required: true },
      { name: "DAM TATTOO", required: false },
      { name: "BIRTH DATE", required: false },
      { name: "MEASURED DATE", required: false },
      { name: "COW WEIGHT", required: false },
      { name: "COW HEIGHT", required: false },
      { name: "CONDITION", required: false },
      { name: "DOCILITY", required: false },
      { name: "DISPOSAL", required: false },
      { name: "DISPOSAL DATE", required: false },
      { name: "ELEC ID", required: false },
      { name: "FS MSURD DATE", required: false },
      { name: "CLAW SET", required: false },
      { name: "FOOT ANGLE", required: false },
      { name: "DIET", required: false },
      { name: "FS COMMENT", required: false },
    ],
  },
  {
    id: "aaa_foot_score",
    name: "Foot Score Entry",
    association: "American Angus Association",
    description: "Foot score data — claw set, foot angle, diet info.",
    headerRow: 1,
    columns: [
      { name: "CUST ID", required: true },
      { name: "2nd CUST ID", required: false },
      { name: "ASSN", required: true },
      { name: "ASSN NUM", required: true },
      { name: "TAG", required: true },
      { name: "TATT", required: false },
      { name: "ELEC ID", required: false },
      { name: "BIRTH DATE", required: true },
      { name: "SEX", required: true },
      { name: "DAM ASSN", required: true },
      { name: "DAM ASSN NUM", required: true },
      { name: "DAM TAG", required: false },
      { name: "SIRE ASSN", required: false },
      { name: "SIRE ASSN NUM", required: false },
      { name: "SIRE TAG", required: false },
      { name: "SIRE GROUP", required: true },
      { name: "MSURD DATE", required: true },
      { name: "CLAW SET", required: true },
      { name: "FOOT ANGLE", required: true },
      { name: "DIET", required: true },
      { name: "COMMENT", required: false },
    ],
  },
  {
    id: "aaa_registration",
    name: "Registrations",
    association: "American Angus Association",
    description: "Register new calves — requires sire/dam reg numbers, birth info.",
    headerRow: 2,
    columns: [
      { name: "CALF TAG", required: true },
      { name: "SEX", required: true },
      { name: "BIRTH DATE", required: true },
      { name: "ANGUS NAME", required: true },
      { name: "PRIMARY ID", required: true },
      { name: "TATTOO/ BRAND", required: true },
      { name: "840 EID", required: false },
      { name: "SECONDARY ID", required: false },
      { name: "ARTIFICIAL INSEMINATION?", required: true },
      { name: "TWIN INDICATOR", required: true },
      { name: "SIRE REG", required: true },
      { name: "SIRE NAME", required: false },
      { name: "DAM TAG", required: false },
      { name: "DAM TATTOO", required: false },
      { name: "DAM REG", required: true },
      { name: "DAM NAME", required: false },
      { name: "FIRST OWNER", required: true },
      { name: "BULL PERMIT", required: false },
      { name: "PERMIT TYPE", required: false },
      { name: "EMBRYO TRANSPLANT?", required: true },
      { name: "IVF?", required: false },
      { name: "EMBRYO REMOVAL DATE", required: false },
      { name: "STORE ELECTRONICALLY?", required: true },
      { name: "BIRTH WEIGHT", required: false },
      { name: "BIRTH GROUP CODE", required: false },
      { name: "CALVING EASE", required: false },
    ],
  },
  {
    id: "aaa_registration_transfer",
    name: "Registrations with Transfers",
    association: "American Angus Association",
    description: "Register and transfer ownership in one submission — includes buyer info and service sires.",
    headerRow: 2,
    columns: [
      { name: "CALF TAG", required: true },
      { name: "SEX", required: true },
      { name: "BIRTH DATE", required: true },
      { name: "ANGUS NAME", required: true },
      { name: "PRIMARY ID", required: true },
      { name: "TATTOO/ BRAND", required: true },
      { name: "840 EID", required: false },
      { name: "SECONDARY ID", required: false },
      { name: "ARTIFICIAL INSEMINATION?", required: true },
      { name: "TWIN INDICATOR", required: true },
      { name: "SIRE REG", required: true },
      { name: "SIRE NAME", required: false },
      { name: "DAM TAG", required: true },
      { name: "DAM TATTOO", required: true },
      { name: "DAM REG", required: true },
      { name: "DAM NAME", required: false },
      { name: "FIRST OWNER", required: true },
      { name: "SALE DATE", required: true },
      { name: "RETAIN INTEREST?", required: true },
      { name: "COW OPEN?", required: true },
      { name: "BUYER 1 CUST CODE", required: true },
      { name: "BUYER 1 NAME", required: true },
      { name: "BUYER 1 ADDRESS", required: true },
      { name: "BUYER 1 CITY", required: true },
      { name: "BUYER 1 STATE / PROVINCE", required: true },
      { name: "BUYER 1 ZIP / POSTAL CODE", required: false },
      { name: "BUYER 1 EMAIL ADDRESS", required: false },
    ],
  },
  {
    id: "aaa_scrotal",
    name: "Scrotal Records",
    association: "American Angus Association",
    description: "Scrotal circumference measurements for bulls.",
    headerRow: 1,
    columns: [
      { name: "CUST CODE", required: true },
      { name: "CALF ASSN NUM", required: false },
      { name: "CALF ASSN", required: false },
      { name: "DAM ASSN NUM", required: true },
      { name: "DAM ASSN", required: true },
      { name: "DAM TAG", required: true },
      { name: "CALF TAG", required: true },
      { name: "TATTOO", required: false },
      { name: "BIRTH DATE", required: true },
      { name: "SC MEASURED DATE", required: true },
      { name: "SC", required: true, description: "Scrotal circumference in cm" },
      { name: "ELEC ID", required: false },
    ],
  },
  {
    id: "aaa_yearling",
    name: "Yearling Records",
    association: "American Angus Association",
    description: "Yearling weights, hip heights, scrotal, docility, foot scores, pelvic, and RTS.",
    headerRow: 1,
    columns: [
      { name: "CUST CODE", required: true },
      { name: "2nd CUST", required: false },
      { name: "CALF ASSN NUM", required: false },
      { name: "CALF ASSN", required: false },
      { name: "DAM ASSN NUM", required: true },
      { name: "DAM ASSN", required: true },
      { name: "DAM TAG", required: true },
      { name: "DAM BIRTH DATE", required: false },
      { name: "SIRE ASSN NUM", required: false },
      { name: "SIRE ASSN", required: false },
      { name: "SIRE TAG", required: false },
      { name: "SIRE GROUP", required: false },
      { name: "CALF TAG", required: true },
      { name: "CALF SEX", required: true },
      { name: "TATTOO /BRAND", required: false },
      { name: "BIRTH DATE", required: true },
      { name: "TWIN", required: false },
      { name: "ET", required: false },
      { name: "IVF", required: false },
      { name: "WEIGH DATE", required: true },
      { name: "WEIGHT", required: true },
      { name: "GROUP", required: false },
      { name: "HIP HT MEASURE DATE", required: false },
      { name: "HIP HT", required: false },
      { name: "SC MEASURED DATE", required: false },
      { name: "SC", required: false },
      { name: "CALF DOCILITY", required: false },
      { name: "FOOT SCORE MSURD DATE", required: false },
      { name: "FOOT CLAW SET", required: false },
      { name: "FOOT ANGLE", required: false },
      { name: "FOOT SCORE DIET", required: false },
      { name: "FOOT SCORE COMMENT", required: false },
      { name: "ELEC ID", required: false },
    ],
  },
];

// Quick lookup by ID
export const getTemplateById = (id: string): BreedTemplate | undefined =>
  ANGUS_TEMPLATES.find((t) => t.id === id);

// All available templates across associations
export const ALL_TEMPLATES: BreedTemplate[] = [
  ...ANGUS_TEMPLATES,
  // Future: HEREFORD_TEMPLATES, SIMMENTAL_TEMPLATES, etc.
];
