// src/lib/project-report-pdf.ts
// Generates a branded PDF report for a completed Cow Work project.
// Uses jsPDF + jspdf-autotable. Matches ChuteSide design system.

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ── Colors ──
const NAVY: [number, number, number] = [14, 38, 70];
const TEAL: [number, number, number] = [85, 186, 170];
const GOLD: [number, number, number] = [243, 209, 42];
const WHITE: [number, number, number] = [255, 255, 255];
const RED: [number, number, number] = [212, 24, 61];
const GRAY: [number, number, number] = [113, 113, 130];

// ── Layout ──
const PW = 215.9; // letter width mm
const PH = 279.4; // letter height mm
const ML = 16;
const MR = 16;
const BODY_W = PW - ML - MR;

function today() {
  return new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
}

export interface ReportAnimal {
  tag: string;
  tag_color?: string;
  sex?: string;
  type?: string;
  breed?: string;
  year_born?: string;
  weight?: number | null;
  preg_stage?: string | null;
  bse_result?: string | null;
  breeding_sire?: string | null;
  breeding_type?: string | null;
  estrus_status?: string | null;
  scrotal?: number | null;
  sale_weight?: number | null;
  purchase_price?: number | null;
  purchase_source?: string | null;
  memo?: string | null;
  is_new_animal?: boolean;
}

export interface ReportProduct {
  name: string;
  dosage?: string;
  route?: string;
}

export interface ReportRecon {
  matched: number;
  missing: number;
  extra: number;
  missingTags: string[];
  extraTags: string[];
}

export interface ProjectReportParams {
  projectName: string;
  projectDate: string;
  projectType: string;
  group: string;
  location: string;
  headExpected: number;
  headWorked: number;
  operationName: string;
  animals: ReportAnimal[];
  products: ReportProduct[];
  recon?: ReportRecon | null;
  closingNotes?: string;
  // Toggle sections
  includeSummary?: boolean;
  includeMetrics?: boolean;
  includeAnimalDetail?: boolean;
  includeRecon?: boolean;
  includeProducts?: boolean;
}

export function generateProjectReportPDF(params: ProjectReportParams): void {
  const {
    projectName, projectDate, projectType, group, location,
    headExpected, headWorked, operationName, animals, products,
    recon, closingNotes,
    includeSummary = true, includeMetrics = true,
    includeAnimalDetail = true, includeRecon = true, includeProducts = true,
  } = params;

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });
  let y = 0;

  // ── Header ──
  function drawHeader() {
    doc.setFillColor(...NAVY);
    doc.rect(0, 0, PW, 26, "F");
    doc.setDrawColor(...TEAL);
    doc.setLineWidth(0.8);
    doc.line(0, 26, PW, 26);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...WHITE);
    doc.text("Project Report", ML, 11);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEAL);
    doc.text(projectName, ML, 19);

    doc.setFontSize(9);
    doc.setTextColor(...WHITE);
    doc.text(operationName, PW - MR, 11, { align: "right" });
    doc.setTextColor(...TEAL);
    doc.text(today(), PW - MR, 19, { align: "right" });

    y = 32;
  }

  // ── Footer ──
  function drawFooter(pageNum: number) {
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(ML, PH - 14, PW - MR, PH - 14);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.text("Generated by ChuteSide Solutions", ML, PH - 9);
    doc.text(`Page ${pageNum}`, PW - MR, PH - 9, { align: "right" });
  }

  function checkPageBreak(needed: number, pageNum: { val: number }) {
    if (y + needed > PH - 20) {
      drawFooter(pageNum.val);
      doc.addPage();
      pageNum.val++;
      drawHeader();
    }
  }

  function sectionTitle(text: string) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...NAVY);
    doc.text(text, ML, y);
    y += 2;
    doc.setDrawColor(...TEAL);
    doc.setLineWidth(0.5);
    doc.line(ML, y, ML + 40, y);
    y += 5;
  }

  function kvRow(label: string, value: string) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...GRAY);
    doc.text(label, ML, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...NAVY);
    doc.text(value, ML + 40, y);
    y += 5;
  }

  const pageNum = { val: 1 };
  drawHeader();

  // ═══════════════ SUMMARY ═══════════════
  if (includeSummary) {
    sectionTitle("PROJECT SUMMARY");
    kvRow("Project:", projectName);
    kvRow("Date:", projectDate);
    kvRow("Type:", projectType);
    kvRow("Group:", group || "—");
    kvRow("Location:", location || "—");
    kvRow("Head Expected:", headExpected ? String(headExpected) : "—");
    kvRow("Head Worked:", String(headWorked));
    if (closingNotes) {
      kvRow("Notes:", closingNotes);
    }
    y += 4;
  }

  // ═══════════════ METRICS ═══════════════
  if (includeMetrics && animals.length > 0) {
    checkPageBreak(40, pageNum);
    sectionTitle("METRICS");

    const weighedAnimals = animals.filter(a => a.weight);
    const avgWeight = weighedAnimals.length > 0
      ? Math.round(weighedAnimals.reduce((s, a) => s + Number(a.weight), 0) / weighedAnimals.length)
      : null;

    if (projectType === "PREG") {
      const confirmed = animals.filter(a => a.preg_stage === "Confirmed").length;
      const open = animals.filter(a => a.preg_stage === "Open").length;
      const suspect = animals.filter(a => a.preg_stage === "Suspect").length;
      const total = animals.length || 1;
      kvRow("Confirmed:", `${confirmed} (${Math.round((confirmed / total) * 100)}%)`);
      kvRow("Open:", `${open} (${Math.round((open / total) * 100)}%)`);
      kvRow("Suspect:", `${suspect} (${Math.round((suspect / total) * 100)}%)`);
    } else if (projectType === "BSE") {
      const pass = animals.filter(a => a.bse_result === "Pass").length;
      const fail = animals.filter(a => a.bse_result === "Fail" || a.bse_result === "Permanent Fail").length;
      const scrotalAnimals = animals.filter(a => a.scrotal);
      const avgScrotal = scrotalAnimals.length > 0
        ? (scrotalAnimals.reduce((s, a) => s + Number(a.scrotal), 0) / scrotalAnimals.length).toFixed(1)
        : "—";
      kvRow("Pass:", String(pass));
      kvRow("Fail:", String(fail));
      kvRow("Avg Scrotal:", `${avgScrotal} cm`);
    } else if (["AI", "BREED", "ET", "TO"].includes(projectType)) {
      const sires = new Set(animals.map(a => a.breeding_sire).filter(Boolean));
      kvRow("Bred:", String(animals.filter(a => a.breeding_sire || a.breeding_type).length));
      kvRow("Sires Used:", String(sires.size));
      if (sires.size > 0) {
        const sireMap = new Map<string, number>();
        animals.forEach(a => { if (a.breeding_sire) sireMap.set(a.breeding_sire, (sireMap.get(a.breeding_sire) || 0) + 1); });
        const sireList = [...sireMap.entries()].sort((a, b) => b[1] - a[1]).map(([s, c]) => `${s} (${c})`).join(", ");
        kvRow("Sire Detail:", sireList);
      }
    } else if (projectType === "SALE") {
      const saleAnimals = animals.filter(a => a.sale_weight);
      const avgSale = saleAnimals.length > 0
        ? Math.round(saleAnimals.reduce((s, a) => s + Number(a.sale_weight), 0) / saleAnimals.length)
        : null;
      const totalLbs = saleAnimals.reduce((s, a) => s + Number(a.sale_weight), 0);
      if (avgSale) kvRow("Avg Sale Wt:", `${avgSale} lbs`);
      if (totalLbs) kvRow("Total Lbs:", `${totalLbs.toLocaleString()} lbs`);
    } else if (projectType === "PURCH") {
      const priceAnimals = animals.filter(a => a.purchase_price);
      const avgPrice = priceAnimals.length > 0
        ? Math.round(priceAnimals.reduce((s, a) => s + Number(a.purchase_price), 0) / priceAnimals.length)
        : null;
      const totalCost = priceAnimals.reduce((s, a) => s + Number(a.purchase_price), 0);
      if (avgPrice) kvRow("Avg Price:", `$${avgPrice}`);
      if (totalCost) kvRow("Total Cost:", `$${totalCost.toLocaleString()}`);
    }

    if (avgWeight) kvRow("Avg Weight:", `${avgWeight} lbs`);
    y += 4;
  }

  // ═══════════════ PRODUCTS ═══════════════
  if (includeProducts && products.length > 0) {
    checkPageBreak(20, pageNum);
    sectionTitle("PRODUCTS USED");
    autoTable(doc, {
      startY: y,
      margin: { left: ML, right: MR },
      head: [["Product", "Dosage", "Route"]],
      body: products.map(p => [p.name, p.dosage || "—", p.route || "—"]),
      styles: { fontSize: 8, cellPadding: 2, font: "helvetica" },
      headStyles: { fillColor: NAVY, textColor: WHITE, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [245, 245, 240] },
    });
    y = (doc as any).lastAutoTable?.finalY + 6 || y + 20;
  }

  // ═══════════════ RECONCILIATION ═══════════════
  if (includeRecon && recon) {
    checkPageBreak(30, pageNum);
    sectionTitle("RECONCILIATION");
    kvRow("Matched:", String(recon.matched));
    kvRow("Missing:", String(recon.missing));
    kvRow("Extra:", String(recon.extra));

    if (recon.missingTags.length > 0) {
      y += 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(...RED);
      doc.text("Missing Tags:", ML, y);
      y += 4;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(...NAVY);
      const missingText = recon.missingTags.join(", ");
      const lines = doc.splitTextToSize(missingText, BODY_W);
      doc.text(lines, ML, y);
      y += lines.length * 3.5 + 2;
    }

    if (recon.extraTags.length > 0) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(232, 116, 97);
      doc.text("Extra Tags:", ML, y);
      y += 4;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(...NAVY);
      const extraText = recon.extraTags.join(", ");
      const lines = doc.splitTextToSize(extraText, BODY_W);
      doc.text(lines, ML, y);
      y += lines.length * 3.5 + 2;
    }
    y += 4;
  }

  // ═══════════════ ANIMAL DETAIL ═══════════════
  if (includeAnimalDetail && animals.length > 0) {
    checkPageBreak(20, pageNum);
    sectionTitle("ANIMAL DETAIL");

    // Build columns based on work type
    const head: string[] = ["#", "Tag"];
    const bodyFn = (a: ReportAnimal, i: number): string[] => {
      const row: string[] = [String(i + 1), a.tag || "?"];
      return row;
    };

    if (projectType === "PREG") {
      head.push("Preg Stage", "Days", "Fetal Sex", "Weight", "Notes");
      const body = animals.map((a, i) => [
        String(i + 1), a.tag, a.preg_stage || "—",
        a.weight ? String(a.weight) : "—",
        a.memo || "",
      ]);
      autoTable(doc, {
        startY: y, margin: { left: ML, right: MR },
        head: [["#", "Tag", "Preg Stage", "Weight", "Notes"]],
        body,
        styles: { fontSize: 7, cellPadding: 1.5, font: "helvetica" },
        headStyles: { fillColor: NAVY, textColor: WHITE, fontStyle: "bold" },
        alternateRowStyles: { fillColor: [245, 245, 240] },
        columnStyles: { 0: { cellWidth: 8 }, 1: { cellWidth: 18 }, 4: { cellWidth: 50 } },
      });
    } else if (projectType === "BSE") {
      const body = animals.map((a, i) => [
        String(i + 1), a.tag, a.bse_result || "—",
        a.scrotal ? String(a.scrotal) : "—",
        a.weight ? String(a.weight) : "—",
      ]);
      autoTable(doc, {
        startY: y, margin: { left: ML, right: MR },
        head: [["#", "Tag", "Result", "Scrotal", "Weight"]],
        body,
        styles: { fontSize: 7, cellPadding: 1.5, font: "helvetica" },
        headStyles: { fillColor: NAVY, textColor: WHITE, fontStyle: "bold" },
        alternateRowStyles: { fillColor: [245, 245, 240] },
        columnStyles: { 0: { cellWidth: 8 }, 1: { cellWidth: 18 } },
      });
    } else if (["AI", "BREED", "ET", "TO"].includes(projectType)) {
      const body = animals.map((a, i) => [
        String(i + 1), a.tag, a.breeding_sire || "—",
        a.breeding_type || "—", a.estrus_status || "—",
        a.weight ? String(a.weight) : "—",
      ]);
      autoTable(doc, {
        startY: y, margin: { left: ML, right: MR },
        head: [["#", "Tag", "Sire", "Method", "Estrus", "Weight"]],
        body,
        styles: { fontSize: 7, cellPadding: 1.5, font: "helvetica" },
        headStyles: { fillColor: NAVY, textColor: WHITE, fontStyle: "bold" },
        alternateRowStyles: { fillColor: [245, 245, 240] },
        columnStyles: { 0: { cellWidth: 8 }, 1: { cellWidth: 18 } },
      });
    } else {
      // Generic: tag, type, weight, notes
      const body = animals.map((a, i) => [
        String(i + 1), a.tag, a.type || "—",
        a.weight ? String(a.weight) : "—", a.memo || "",
      ]);
      autoTable(doc, {
        startY: y, margin: { left: ML, right: MR },
        head: [["#", "Tag", "Type", "Weight", "Notes"]],
        body,
        styles: { fontSize: 7, cellPadding: 1.5, font: "helvetica" },
        headStyles: { fillColor: NAVY, textColor: WHITE, fontStyle: "bold" },
        alternateRowStyles: { fillColor: [245, 245, 240] },
        columnStyles: { 0: { cellWidth: 8 }, 1: { cellWidth: 18 }, 4: { cellWidth: 50 } },
      });
    }

    y = (doc as any).lastAutoTable?.finalY + 6 || y + 20;
  }

  // ── Footer on last page ──
  drawFooter(pageNum.val);

  // ── Save ──
  const safeName = projectName.replace(/[^a-zA-Z0-9]/g, "_");
  doc.save(`${safeName}_Report.pdf`);
}
