// src/lib/protocol-pdf.ts
// Generates a branded PDF for a customer's assigned protocols.
// Uses jsPDF + jspdf-autotable for table rendering.
// Design system: Inter font approximated with Helvetica (jsPDF built-in),
// navy #0E2646, teal #55BAAA, gold #F3D12A, cream #F5F5F0.

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ── Types ──
interface ProtocolProduct {
  product_name: string;
  dosage: string | null;
  route: string | null;
  notes: string | null;
}

interface ProtocolEvent {
  event_name: string;
  scheduled_date: string | null;
  event_status: string;
  recommended_products: ProtocolProduct[];
  completion_notes: string;
  actual_head_count: number | null;
}

interface ProtocolSection {
  animal_class: string;
  estimated_head_count: number | null;
  stages: ProtocolEvent[];
}

interface PDFParams {
  customerName: string;
  practiceName: string;
  year: number;
  sections: ProtocolSection[];
}

// ── Colors ──
const NAVY = [14, 38, 70] as const;     // #0E2646
const TEAL = [85, 186, 170] as const;   // #55BAAA
const GOLD = [243, 209, 42] as const;   // #F3D12A
const WHITE = [255, 255, 255] as const;
const CREAM = [245, 245, 240] as const; // #F5F5F0
const TEXT = [26, 26, 26] as const;     // #1A1A1A
const MUTED = [113, 113, 130] as const; // #717182
const BORDER = [212, 212, 208] as const;// #D4D4D0

// ── Helpers ──
function formatDate(dateStr: string | null): string {
  if (!dateStr) return "TBD";
  const d = new Date(dateStr + "T00:00:00");
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

function today(): string {
  return new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
}

// Page dimensions (US Letter in mm)
const PW = 215.9;  // page width
const PH = 279.4;  // page height
const ML = 15;     // margin left
const MR = 15;     // margin right
const CW = PW - ML - MR; // content width

// ── Main export function ──
export function generateProtocolPDF(params: PDFParams): void {
  const { customerName, practiceName, year, sections } = params;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "letter" });

  let y = 0;
  let pageNum = 1;
  const totalSections = sections.length;

  // Count total events for the summary
  const totalEvents = sections.reduce((sum, s) => sum + s.stages.filter(st => st.recommended_products.length > 0).length, 0);
  const totalProducts = sections.reduce((sum, s) =>
    sum + s.stages.reduce((eSum, st) => eSum + st.recommended_products.length, 0), 0);

  // ────────────────────────────────────
  // Header bar (appears on every page)
  // ────────────────────────────────────
  function drawHeader() {
    // Navy bar
    doc.setFillColor(...NAVY);
    doc.rect(0, 0, PW, 24, "F");

    // Teal accent line
    doc.setDrawColor(...TEAL);
    doc.setLineWidth(0.8);
    doc.line(0, 24, PW, 24);

    // Practice name — left side
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...WHITE);
    doc.text(practiceName, ML, 10);

    // Customer name — left side, teal
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEAL);
    doc.text(customerName, ML, 17);

    // Date — right side
    doc.setFontSize(9);
    doc.setTextColor(...WHITE);
    doc.text(today(), PW - MR, 10, { align: "right" });

    // Year label — right side, teal
    doc.setTextColor(...TEAL);
    doc.text(`${year} Vaccination Protocols`, PW - MR, 17, { align: "right" });

    y = 30;
  }

  // ────────────────────────────────────
  // Footer (appears on every page)
  // ────────────────────────────────────
  function drawFooter() {
    const fy = PH - 10;
    doc.setDrawColor(...BORDER);
    doc.setLineWidth(0.3);
    doc.line(ML, fy - 3, PW - MR, fy - 3);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text("Generated by ChuteSide Solutions", ML, fy);
    doc.text(`Page ${pageNum}`, PW - MR, fy, { align: "right" });
  }

  // ────────────────────────────────────
  // New page helper
  // ────────────────────────────────────
  function newPage() {
    drawFooter();
    doc.addPage();
    pageNum++;
    drawHeader();
  }

  // Check if we need a new page (min space needed in mm)
  function needsPage(minSpace: number) {
    if (y + minSpace > PH - 20) {
      newPage();
    }
  }

  // ────────────────────────────────────
  // PAGE 1: Header + Summary
  // ────────────────────────────────────
  drawHeader();

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...NAVY);
  doc.text("Vaccination Protocol Summary", ML, y + 8);
  y += 16;

  // Summary box
  doc.setFillColor(...CREAM);
  doc.roundedRect(ML, y, CW, 28, 2, 2, "F");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...TEXT);
  doc.text(`Customer: ${customerName}`, ML + 4, y + 7);
  doc.text(`Protocol Year: ${year}`, ML + 4, y + 13);
  doc.text(`Animal Classes: ${totalSections}`, ML + 4, y + 19);
  doc.text(`Working Events: ${totalEvents}`, ML + CW / 2, y + 7);
  doc.text(`Total Products: ${totalProducts}`, ML + CW / 2, y + 13);

  // Head counts
  const headStr = sections
    .filter(s => s.estimated_head_count)
    .map(s => `${s.animal_class}: ${s.estimated_head_count}`)
    .join("  ·  ");
  if (headStr) {
    doc.text(`Est. Head: ${headStr}`, ML + CW / 2, y + 19);
  }

  y += 34;

  // ────────────────────────────────────
  // Protocol sections (one per animal class)
  // ────────────────────────────────────
  for (const section of sections) {
    const activeStages = section.stages.filter(s => s.recommended_products.length > 0);
    if (activeStages.length === 0) continue;

    needsPage(30);

    // Animal class header bar
    doc.setFillColor(...NAVY);
    doc.roundedRect(ML, y, CW, 10, 1.5, 1.5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(...WHITE);
    doc.text(section.animal_class.toUpperCase(), ML + 4, y + 7);

    if (section.estimated_head_count) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...TEAL);
      doc.text(`${section.estimated_head_count} head`, PW - MR - 4, y + 7, { align: "right" });
    }
    y += 14;

    // Each working event
    for (const stage of activeStages) {
      needsPage(25);

      // Event name + date
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(...NAVY);
      doc.text(stage.event_name, ML, y + 5);

      if (stage.scheduled_date) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(...MUTED);
        doc.text(formatDate(stage.scheduled_date), PW - MR, y + 5, { align: "right" });
      }

      // Teal left accent
      doc.setFillColor(...TEAL);
      doc.rect(ML, y, 1.5, 8, "F");

      y += 10;

      // Product table
      const tableData = stage.recommended_products.map(p => [
        p.product_name,
        p.dosage || "—",
        p.route || "—",
        p.notes ? (p.notes.length > 60 ? p.notes.substring(0, 57) + "..." : p.notes) : "",
      ]);

      autoTable(doc, {
        startY: y,
        margin: { left: ML, right: MR },
        head: [["Product", "Dosage", "Route", "Notes"]],
        body: tableData,
        styles: {
          font: "helvetica",
          fontSize: 8.5,
          cellPadding: { top: 1.5, bottom: 1.5, left: 2, right: 2 },
          textColor: TEXT as unknown as number[],
          lineColor: BORDER as unknown as number[],
          lineWidth: 0.2,
        },
        headStyles: {
          fillColor: NAVY as unknown as number[],
          textColor: WHITE as unknown as number[],
          fontStyle: "bold",
          fontSize: 8,
        },
        alternateRowStyles: {
          fillColor: CREAM as unknown as number[],
        },
        columnStyles: {
          0: { cellWidth: CW * 0.28 },  // Product
          1: { cellWidth: CW * 0.18 },  // Dosage
          2: { cellWidth: CW * 0.12 },  // Route
          3: { cellWidth: CW * 0.42 },  // Notes
        },
        didDrawPage: () => {
          // If autotable triggers a new page, redraw header
          drawHeader();
        },
      });

      // Get the final Y from autotable
      y = (doc as any).lastAutoTable?.finalY || y + 20;
      y += 6;
    }

    y += 4; // Extra space between animal classes
  }

  // ────────────────────────────────────
  // Calendar section
  // ────────────────────────────────────
  needsPage(50);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...NAVY);
  doc.text("Scheduled Events Calendar", ML, y + 6);
  y += 12;

  // Build calendar rows from all events
  const calendarRows: string[][] = [];
  for (const section of sections) {
    for (const stage of section.stages) {
      if (stage.recommended_products.length === 0) continue;
      calendarRows.push([
        section.animal_class,
        stage.event_name,
        formatDate(stage.scheduled_date),
        stage.event_status === "completed" ? "Completed" : stage.event_status === "overdue" ? "Overdue" : "Upcoming",
        stage.recommended_products.length.toString(),
      ]);
    }
  }

  if (calendarRows.length > 0) {
    autoTable(doc, {
      startY: y,
      margin: { left: ML, right: MR },
      head: [["Animal Class", "Working Event", "Scheduled Date", "Status", "Products"]],
      body: calendarRows,
      styles: {
        font: "helvetica",
        fontSize: 9,
        cellPadding: { top: 2, bottom: 2, left: 3, right: 3 },
        textColor: TEXT as unknown as number[],
        lineColor: BORDER as unknown as number[],
        lineWidth: 0.2,
      },
      headStyles: {
        fillColor: NAVY as unknown as number[],
        textColor: WHITE as unknown as number[],
        fontStyle: "bold",
      },
      alternateRowStyles: {
        fillColor: CREAM as unknown as number[],
      },
      didDrawPage: () => {
        drawHeader();
      },
    });

    y = (doc as any).lastAutoTable?.finalY || y + 20;
  }

  // ────────────────────────────────────
  // Final footer on last page
  // ────────────────────────────────────
  drawFooter();

  // ────────────────────────────────────
  // Go back and add footers to all pages
  // ────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const fy = PH - 10;
    doc.setDrawColor(...BORDER);
    doc.setLineWidth(0.3);
    doc.line(ML, fy - 3, PW - MR, fy - 3);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text("Generated by ChuteSide Solutions", ML, fy);
    doc.text(`Page ${i} of ${totalPages}`, PW - MR, fy, { align: "right" });
  }

  // ────────────────────────────────────
  // Save
  // ────────────────────────────────────
  const filename = `${customerName.replace(/\s+/g, "_")}_Protocols_${year}.pdf`;
  doc.save(filename);
}
